dataset: "JVS"

path:
  corpus_path: "/path/to/jvs"
  lexicon_path: ""
  raw_path: "./raw_data/JVS"
  lab_path: "./lab/JVS"
  preprocessed_path: "./preprocessed_data/JVS"

text:
  text_cleaners: ["english_cleaners"]
  language: "ja"

accent:
  use_accent: True