path:
  ckpt_path: "./output/ckpt/JVS-VCTK_0.5_50000_woge2e"
  log_path: "./output/log/JVS-VCTK_langclf_0.5_50000_woge2e"
  result_path: "./output/result/JVS-VCTK_langclf_0.5_50000_woge2e"
  discriminator_path: "/home/sarulab/aya_watanabe/デスクトップ/work/FastSpawn-JVS/Multilingual-Speaker-Encoder-with-Domain-Adaptation/output_woGE2E/ckpt_sg_discriminator_woGE2E_epoch_2400_batch_id_6.pth"
optimizer:
  batch_size: 16
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 50000
  log_step: 100
  synth_step: 1000
  val_step: 1000
  save_step: 10000
dataparallel: False
lambda: 0.5